<h1><center><strong> Eval Models Results</center></h1>

Мы использовали методы кластеризации для создания различных датасетов, а затем проверяли их с помощью Random Forest, чтобы определить наилучший подбор кластеров. В результате мы получили два претендента: **DBSCAN_generated_features_PCA** с точностью 0.99344 и **AgglomerativeClustering_generated_features** с точностью 0.99075. Теперь нам необходимо более подробно изучить, как именно распределены данные между кластерами в обоих случаях, чтобы понять, какой из алгоритмов кластеризации более эффективно разделяет данные.

<center><strong>DBSCAN_generated_features_PCA</center>

In [17]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import euclidean_distances

customer_data = pd.read_csv('../../data/raw_data/customer_data.csv')  
dbscan_data = pd.read_csv('../../data/processed_data/train_models_data/data_with_PCA/data_with_generated_features/DBSCAN_generated_features_PCA.csv') 

features = dbscan_data.drop(columns=['Cluster'])

scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

clusters = dbscan_data['Cluster'].unique()

closest_points = []

for cluster in clusters:
    cluster_data = features_scaled[dbscan_data['Cluster'] == cluster]
    
    cluster_center = np.mean(cluster_data, axis=0)
    
    distances = euclidean_distances(cluster_data, cluster_center.reshape(1, -1))
    closest_point_index = np.argmin(distances)
    
    customer_index = dbscan_data[dbscan_data['Cluster'] == cluster].index[closest_point_index]
    closest_point = customer_data.iloc[customer_index]
    
    closest_points.append(closest_point)

result_df = pd.DataFrame(closest_points)
result_df

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
421,C10436,1452.437463,1.0,0.00,0.0,0.00,114.918715,0.000000,0.0,0.000000,0.25,3,0,1500.0,331.670616,479.771774,0.000000,12
1159,C11202,230.823876,1.0,1842.33,0.0,1842.33,0.000000,0.916667,0.0,0.833333,0.00,0,12,3000.0,1651.128297,174.020429,0.333333,12

<center><strong>AgglomerativeClustering_generated_features</center>

In [19]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import euclidean_distances

customer_data = pd.read_csv('../../data/raw_data/customer_data.csv')  
agg_clustering_data = pd.read_csv('../../data/processed_data/train_models_data/data_without_PCA/data_with_generated_features/AgglomerativeClustering_generated_features.csv') 

features = agg_clustering_data.drop(columns=['Cluster'])

scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

clusters = agg_clustering_data['Cluster'].unique()

closest_points = []

for cluster in clusters:
    cluster_data = features_scaled[agg_clustering_data['Cluster'] == cluster]
    
    cluster_center = np.mean(cluster_data, axis=0)
    
    distances = euclidean_distances(cluster_data, cluster_center.reshape(1, -1))
    closest_point_index = np.argmin(distances)
    
    customer_index = agg_clustering_data[agg_clustering_data['Cluster'] == cluster].index[closest_point_index]
    closest_point = customer_data.iloc[customer_index]
    
    closest_points.append(closest_point)

result_df = pd.DataFrame(closest_points)
result_df

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
5959,C16125,252.717781,1.000000,463.34,0.0,463.34,0.0,0.833333,0.0,0.833333,0.0,0,10,4000.0,162.949236,184.464721,0.0,12
6058,C16229,387.967458,1.000000,944.49,0.0,944.49,0.0,1.000000,0.0,1.000000,0.0,0,23,1000.0,831.708548,218.808215,0.0,12
6793,C16981,14.480094,0.571429,134.60,0.0,134.60,0.0,0.571429,0.0,0.428571,0.0,0,4,3000.0,155.845232,102.333285,1.0,7

#### Выводы: можем заметить, что AgglomerativeClustering лучше разделяет данные, так как кластеры более логичные и видима существенная разница между ними с точки зрения экономической логики. В то время как DBSCAN разделил данные на кластеры, которые сложно интерпретировать и практически не имеют смысла.