### Посмотрим, влияет ли наличие дополнительных признаков на качество модели

In [1]:
import pandas as pd
from itertools import combinations_with_replacement

In [2]:
data = pd.read_csv('../../data/processed_data/main_datasets/customer_data_processed.csv')
data.head(5)

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,-1.334348,-0.270075,-0.123104,-0.995909,0.382099,-0.937995,-0.761018,-0.740342,-0.684413,-0.731294,-0.817031,-0.593025,-1.447905,-1.293972,-0.820647,-0.569563,0.341918
1,0.952818,0.116261,-1.686076,-0.995909,-1.095968,1.518317,-1.317061,-0.740342,-0.968008,0.681694,0.768576,-1.389871,0.917344,1.296746,0.887361,0.367302,0.341918
2,0.821240,0.484620,0.589627,1.049267,-1.095968,-0.937995,1.183213,2.441043,-0.968008,-0.731294,-0.817031,0.470539,1.001230,-0.327094,0.437490,-0.569563,0.341918
3,0.233311,0.484620,-0.716780,-0.124802,-1.095968,-0.937995,-1.028337,-0.372966,-0.968008,-0.731294,-0.817031,-0.887118,-1.226399,-0.252615,-0.350894,-0.569563,0.341918
4,0.651964,0.484620,0.775861,-0.995909,1.232229,-0.937995,0.525555,-0.740342,0.660141,-0.731294,-0.817031,0.203820,-0.733677,0.370940,1.566214,-0.569563,0.341918

In [3]:
def calc_stats(col):
    return {
        'mean': col.mean(),
        'std': col.std(),
        'min': col.min(),
        'max': col.max(),
        'skew': col.skew(),
        'median': col.median()
    }

for col1, col2 in combinations_with_replacement(data.columns, 2):
    # Операции над колонками
    if col1 != col2:  # Для суммы - без повторений
        data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
        data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
    
    # Для разности - с повторениями
    data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]

for col in data.columns:
    stats = calc_stats(data[col])
    for stat, value in stats.items():
        data[f'{col}_{stat}'] = value

data

C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_plus_{col2}'] = data[col1] + data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_proizvedenie_{col2}'] = data[col1] * data[col2]
C:\Users\Олег\AppData\Local\Temp\ipykernel_28192\3214947733.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data[f'{col1}_minus_{col2}'] = data[col1] - data[col2]

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,...,PRC_FULL_PAYMENT_minus_TENURE_min,PRC_FULL_PAYMENT_minus_TENURE_max,PRC_FULL_PAYMENT_minus_TENURE_skew,PRC_FULL_PAYMENT_minus_TENURE_median,TENURE_minus_TENURE_mean,TENURE_minus_TENURE_std,TENURE_minus_TENURE_min,TENURE_minus_TENURE_max,TENURE_minus_TENURE_skew,TENURE_minus_TENURE_median
0,-1.334348,-0.270075,-0.123104,-0.995909,0.382099,-0.937995,-0.761018,-0.740342,-0.684413,-0.731294,...,-0.911481,7.173343,1.851724,-0.911481,0.0,0.0,0.0,0.0,0.0,0.0
1,0.952818,0.116261,-1.686076,-0.995909,-1.095968,1.518317,-1.317061,-0.740342,-0.968008,0.681694,...,-0.911481,7.173343,1.851724,-0.911481,0.0,0.0,0.0,0.0,0.0,0.0
2,0.821240,0.484620,0.589627,1.049267,-1.095968,-0.937995,1.183213,2.441043,-0.968008,-0.731294,...,-0.911481,7.173343,1.851724,-0.911481,0.0,0.0,0.0,0.0,0.0,0.0
3,0.233311,0.484620,-0.716780,-0.124802,-1.095968,-0.937995,-1.028337,-0.372966,-0.968008,-0.731294,...,-0.911481,7.173343,1.851724,-0.911481,0.0,0.0,0.0,0.0,0.0,0.0
4,0.651964,0.484620,0.775861,-0.995909,1.232229,-0.937995,0.525555,-0.740342,0.660141,-0.731294,...,-0.911481,7.173343,1.851724,-0.911481,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8632,-2.287829,-1.793336,-0.630131,-0.046930,-1.095968,-0.937995,-0.761018,-0.032825,-0.968008,-0.731294,...,-0.911481,7.173343,1.851724,-0.911481,0.0,0.0,0.0,0.0,0.0,0.0
8633,-1.519536,0.484620,0.256189,-0.995909,0.740787,-0.937995,1.183213,-0.740342,1.179566,-0.731294,...,-0.911481,7.173343,1.851724,-0.911481,0.0,0.0,0.0,0.0,0.0,0.0
8634,-1.619553,-0.204364,0.017501,-0.995909,0.515065,-0.937995,0.869350,-0.740342,0.841878,-0.731294,...,-0.911481,7.173343,1.851724,-0.911481,0.0,0.0,0.0,0.0,0.0,0.0
8635,-1.895547,-0.204364,-1.686076,-0.995909,-1.095968,0.077450,-1.317061,-0.740342,-0.968008,0.244820,...,-0.911481,7.173343,1.851724,-0.911481,0.0,0.0,0.0,0.0,0.0,0.0
8636,-0.180307,-0.959057,0.708012,1.155659,-1.095968,0.420916,0.525555,1.604230,-0.968008,1.090363,...,-0.911481,7.173343,1.851724,-0.911481,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8637 entries, 0 to 8636
Columns: 3094 entries, BALANCE to TENURE_minus_TENURE_median
dtypes: float64(3094)
memory usage: 203.9 MB

In [5]:
data.to_csv('../../data/processed_data/main_datasets/data_with_generated_features.csv', index=False)